import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'java'
    id "com.gradleup.shadow" version "8.3.0"
}

group = 'com.gmail.necnionch.myplugin'
version = '1.2.0'

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
    maven {
        name = 'minecrell'
        url = 'https://repo.minecrell.net/releases'
    }

    // velocity
    maven {
        name = 'papermc-repo'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'net.md-5:bungeecord-api:1.15-SNAPSHOT'

    compileOnly files("libs/CraftSwitcherReportModule-1.1.0.jar")
    compileOnly files("libs/DiscordConnect-1.1b.jar")

    compileOnly files("libs/ServerListPlus-3.4.8-Universal.jar")

    compileOnly files("libs/N8ServerUtils-1.2.0-SNAPSHOT.jar")

    implementation "net.kyori:adventure-platform-bungeecord:4.3.4"

}

tasks.named("shadowJar", ShadowJar) {
    archiveClassifier.set("")
    dependencies {
        exclude "/META-INF/**"
    }
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('bungee.yml') {
        expand props
    }
}
